"""
Shared HTTP client for Layer-1 and Layer-2 checks.

Uses curl_cffi instead of requests so every outbound connection performs a
full TLS fingerprint impersonation of Chrome (JA3/JA4 and HTTP/2 ALPN) rather
than Python's default ssl stack.  This eliminates the most common bot-detection
signal that retailer WAFs rely on.

Realistic request headers are generated by browserforge on each call so the
User-Agent, sec-ch-ua, Accept-Language, etc. match a real browser profile.

Retries with exponential back-off:
  attempt 0 → immediate
  attempt 1 → 1 s delay
  attempt 2 → 2 s delay

Public API
----------
http_get(url, timeout=12) → requests.Response-compatible object
    .status_code, .text, .content, .headers, .url
"""
from __future__ import annotations

import logging
import time
from typing import Optional

from curl_cffi import requests as _cffi
from browserforge.headers import HeaderGenerator, Browser
from checker._response_cache import ResponseCache
from checker._proxy_rotator import get_global_rotator
from config import DEV_CACHE_ENABLED, DEV_CACHE_DIR, PROXY_LIST

log = logging.getLogger(__name__)

# Build a Chrome-130+ header generator once at import time.
# Re-instantiated lazily if needed to avoid import-time network calls.
_HEADER_GEN: Optional[HeaderGenerator] = None
_CACHE: Optional[ResponseCache] = None

_CHROME_IMPERSONATE = "chrome120"   # curl_cffi impersonation target

_MAX_RETRIES   = 3
_RETRY_DELAYS  = (0, 1, 2)         # seconds before each attempt


def _get_generator() -> HeaderGenerator:
    global _HEADER_GEN
    if _HEADER_GEN is None:
        try:
            _HEADER_GEN = HeaderGenerator(browser=[Browser(name='chrome', min_version=120)])
        except Exception as exc:
            log.debug("browserforge HeaderGenerator init failed: %s — using fallback UA", exc)
            _HEADER_GEN = None
    return _HEADER_GEN


def _build_headers() -> dict:
    """Generate a realistic Chrome header set; fall back to a static UA on error."""
    gen = _get_generator()
    if gen is None:
        return {
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            )
        }
    try:
        return dict(gen.generate())
    except Exception as exc:
        log.debug("browserforge.generate() failed: %s", exc)
        return {
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            )
        }


def _get_cache() -> Optional[ResponseCache]:
    global _CACHE
    if not DEV_CACHE_ENABLED:
        return None
    if _CACHE is None:
        _CACHE = ResponseCache(DEV_CACHE_DIR)
    return _CACHE


def _get_proxies() -> Optional[dict]:
    if not PROXY_LIST:
        return None
    rotator = get_global_rotator()
    if rotator is None:
        return None
    return rotator.get_for_curl_cffi()


def http_get(url: str, timeout: int = 12):
    """
    Perform a GET request using curl_cffi with Chrome TLS impersonation and
    realistic browser headers. Retries up to _MAX_RETRIES times on transient errors.

    Returns a curl_cffi Response object exposing:
        .status_code  int
        .text         str
        .content      bytes
        .headers      dict-like
        .url          str  (final URL after redirects)

    Never raises — returns None on exhausted retries or unrecoverable error.
    """
    headers = _build_headers()
    cache = _get_cache()
    fp = None
    if cache is not None:
        fp = ResponseCache.fingerprint(url, method="GET")
        cached = cache.get(fp)
        if cached is not None:
            log.debug("http_get cache hit for %s", url)
            return cached

    proxies = _get_proxies()

    for attempt, delay in enumerate(_RETRY_DELAYS[:_MAX_RETRIES]):
        if delay:
            time.sleep(delay)
        try:
            resp = _cffi.get(
                url,
                impersonate=_CHROME_IMPERSONATE,
                headers=headers,
                timeout=timeout,
                allow_redirects=True,
                proxies=proxies,
            )
            if cache is not None and fp is not None and resp.status_code == 200:
                cache.put(fp, resp)
            return resp
        except _cffi.exceptions.RequestsError as exc:
            log.debug("http_get attempt %d/%d failed for %s: %s", attempt + 1, _MAX_RETRIES, url, exc)
        except Exception as exc:
            log.debug("http_get unexpected error (attempt %d) for %s: %s", attempt + 1, url, exc)

    log.warning("http_get: all %d retries exhausted for %s", _MAX_RETRIES, url)
    return None
